### ISSUE TITLE
Import node_modules not working when bundle is set to true

### ISSUE THREAD

**Issue by alex-w0** [glromeo/esbuild-sass-plugin#74] opened 2022-02-24 09:41 UTC
When I'm trying to import a file from the node_modules with the symbol `~` then it will give me the following error. Writing the full path manually works.

```scss
@import '~dialog-polyfill/dist/dialog-polyfill.css';
``` 

```shell
esbuild.build({
  entryPoints: [
    '....'
  ],
  bundle: true,
  outdir: './css',
  plugins: [esbuildSass.sassPlugin()]
})
.catch(() => {
  process.exit(1)
})

✘ [ERROR] Could not resolve "~dialog-polyfill/dist/dialog-polyfill.css"

    src/sass/formio.form.scss:2:8:
      2 │ @import '~dialog-polyfill/dist/dialog-polyfill.css';

```

**Comment by glromeo** [comment] 2022-02-24 17:58
your issue is likely a css import (i.e. not sass) being tried to be resolved by esbuild …I can’t just see that import in formio so if can’t tell more than that… I am happy to help you troubleshoot this but you have to come up with a github repo where you reproduce the issue

**Comment by alex-w0** [comment] 2022-02-24 18:48
Yes true, it's a common css import which should recognize the tilde as an alias for the node_modules. The formio file just contains the import statement at the beginning. Here is the [repo](https://github.com/alex-w0/esbuild-sass-plugin-demo) for reproducing the issue.

**Comment by glromeo** [comment] 2022-02-25 00:45
the issue here is that sass doesn’t call the plugin importer because it’s a css so the import ends in the css that esbuild is trying to bundle and esbuild has no idea how to deal with ~ indeed if you remove ~ from your example url it builds just fine

**Comment by glromeo** [comment] 2022-02-25 00:47
another option for you is to use the precompile in the plugin to change the url and remove the ~

**Comment by glromeo** [comment] 2022-02-25 01:06
I’m on holidays with just an ipad when back I want to try and add another onResolve to the plugin to male life easier in these situations 

the idea is the following 
```javascript 

var esbuild = require('esbuild');
var esbuildSass = require('esbuild-sass-plugin');

esbuild
  .build({
    entryPoints: ['./src/formio.scss'],
    bundle: true,
    outdir: './css',
    plugins: [esbuildSass.sassPlugin(),
       {name:"temp",setup(build){
      build.onResolve({filter:/~.*css/},({path})=>{
        return {path: require.resolve(path.slice(1))}
      })
    }}],
    
  })
  .catch(() => {
    process.exit(1);
  });

```

**Comment by alex-w0** [comment] 2022-02-25 10:37
> I’m on holidays with just an ipad when back I want to try and add another onResolve to the plugin to male life easier in these situations
> 
> the idea is the following
> 
> ```js
> var esbuild = require('esbuild');
> var esbuildSass = require('esbuild-sass-plugin');
> 
> esbuild
>   .build({
>     entryPoints: ['./src/formio.scss'],
>     bundle: true,
>     outdir: './css',
>     plugins: [esbuildSass.sassPlugin(),
>        {name:"temp",setup(build){
>       build.onResolve({filter:/^~.*css$/},({path})=>{
>         return {path: require.resolve(path.slice(1))}
>       })
>     }}],
>     
>   })
>   .catch(() => {
>     process.exit(1);
>   });
> ```

Yes no worry, writing the full path works fine for me, so this improvement is not really urgent or even tragic when it's not possible. Enjoy your holidays.

**Comment by glromeo** [comment] 2022-02-26 17:56
@alex-w0 you can upgrade to 2.2.4 and add `cssImport: true` to your options
thank you for your example repo!

**Closed** 2022-02-26 17:56 UTC
Labels: enhancement

**Comment by alex-w0** [comment] 2022-02-28 06:56
Thanks works great :rocket: I also didn't know that the `~` is deprecated these days ^^

**Comment by tadman** [comment] 2022-03-02 20:18
Is it `cssImport` or `cssImports` as in the docs?
