### ISSUE TITLE
Pure esbuild sass files with relative assets fails to load

### ISSUE THREAD

**Issue by Hideman85** [glromeo/esbuild-sass-plugin#48] opened 2021-12-09 19:45 UTC
I do have a relative import issue:
```
✘ [ERROR] Could not resolve "./NunitoSans-Bold.ttf"
    sass-plugin-0:/....../LoadingAlert.scss:51:11:
```

The file import a relative sass file

I found other issues on the repo like `@import "../../../fonts/fonts.scss";` and this file is importing the font.

I do see other similar issues on the repo but I don't really get it... I try to find if this is due to dart-sass but no clue either....
Currently this is working with webpack but I do think like https://github.com/glromeo/esbuild-sass-plugin/issues/19 this ise due to special resolver.

What can I do to solve my issue?

**Comment by glromeo** [comment] 2021-12-10 01:51
I never saw an error message like that, can you help me reproduce this issue?
is that you obfuscating the path or is it really `/....../` ???

If you could share the repo that would be great!

**Comment by Hideman85** [comment] 2021-12-10 08:11
Yes I just obfuscated the complete path to ..... I should have put *
The project is a closed source commercial project so I cannot share it but I could see to produce a reproduction case.

**Comment by glromeo** [comment] 2021-12-12 23:27
This actually is a similar issue to #19 indeed...
This little debug plugin shows us that:
```javascript
{
  name: "resolve-assets",
  setup(build) {
    build.onResolve({filter: /./}, ({path, resolveDir, importer, namespace})=>{
      console.log("resolve:", path, resolveDir, importer, namespace)
      return null;
    })
  }
}
```
the issue is not in the plugin but in esbuild trying and resolving the font url from the source file and not the sass file
```
resolve: D:/esbuild-sass-test-case/src/index.js D:/esbuild-sass-test-case  file
resolve: ./NunitoSans-Light.ttf D:\esbuild-sass-test-case\src D:\esbuild-sass-test-case\src\style.scss sass-plugin-0
X [ERROR] Could not resolve "./NunitoSans-Light.ttf"

    sass-plugin-0:D:\Workspace\esbuild-sass-plugin\test\issues\esbuild-sass-test-case\src\style.scss:3:11:
      3 │   src: url("./NunitoSans-Light.ttf");
        ╵            ~~~~~~~~~~~~~~~~~~~~~~~~
```
I am still of the idea that I don't want to take `esbuild-sass-plugin` in the direction taken by the webpack loader
and that's also because these kind of import issues can be solved by coding ad hoc plugins to rewrite the urls.
e.g.
```javascript
    plugins: [
      sassPlugin({
        outputStyle: isProd ? 'compressed' : 'expanded'
      }),{
        name: "resolve-assets",
        setup(build) {
          build.onResolve({filter: /.ttf$/}, (args)=>{
            try {
              return {path: require.resolve(args.path, {paths: ['./fonts']})}
            } catch (e) {
              console.error(e)
              return null;
            }
          })
        }
      }
    ]

```
of course this solution is pretty poor but it might be the starting point for something that works for your project layout.

**NOTE:** The issue is that the importer of the asset (.ttf) is an information that sass has swallowed and neither the plugin or esbuild can have

**Comment by Hideman85** [comment] 2021-12-13 15:39
Thanks for your complete answer, then I'm gonna open an issue in esbuild I don't like the resolve assets hand made fix it does not fit at scale.

**Comment by glromeo** [comment] 2021-12-13 15:44
sorry @Hideman85 but esbuild author can't help you there! 

> NOTE: The issue is that the importer of the asset (.ttf) is an information that sass has swallowed and neither the plugin or esbuild can have

**Comment by Hideman85** [comment] 2021-12-13 15:46
But then this is not usable, we cannot tell all the users:

> _In order to use this plugin you have to manually resolve all your assets_

**Comment by glromeo** [comment] 2021-12-13 16:24
The issue is within SASS and a solution might come from https://github.com/sass/sass/issues/2535
but for now you are probably better off using webpack and [resolve-url-loader](https://github.com/bholloway/resolve-url-loader/tree/v4-maintenance/packages/resolve-url-loader)

**Comment by Hideman85** [comment] 2021-12-13 16:27
Yes currently I'm with webpack + babel + terser and that is horribly slow that's why I was looking to move to esbuild.
Do you think node-sass has the same issue? It might be an alternative too right?

**Comment by glromeo** [comment] 2021-12-14 00:51
Node sass has the same issue but at least it would allow importers to intercept all @imports and one could hack into that to 
rewrite relative urls in absolute that then esbuild could rewrite properly.
node-sass is deprecated so I cannot really invest all that effort to leverage on a feature that's seen by the sass team
as a bug: https://github.com/sass/dart-sass/issues/574

This is the only hope: https://github.com/sass/sass/issues/2535

by the way parcel and rollup have the same issues and what resolve-url-loader does is just crazy!

https://github.com/bholloway/resolve-url-loader/blob/v4-maintenance/packages/resolve-url-loader/docs/how-it-works.md

**Comment by Hideman85** [comment] 2021-12-14 08:17
Wow the resolve-url-loader is indeed crazy :joy: 

Our only hope rely on a issue opened more than 3 years ago :cry: I would say that it would probably happen a day but that does not look like for the near feature.

Maybe we can upvote the issue by adding our case and maybe it would boost it

**Comment by glromeo** [comment] 2021-12-20 03:43
Hi @Hideman85 I just published https://www.npmjs.com/package/esbuild-sass-plugin/v/2.0.0-alpha.0 in npm.
In this version there are few breaking changes but I guess they won't affect your project.
Instead there's the replacement of the old `renderSync` API call with the new `compile` that allows importers to intercept all import resolutions, also the relative ones. 
There's also a `precompile` option that allows re-writing the sass sources before they are compiled by sass which allows global variables but also, in your case, to rewrite urls.

Just switch to 2.0.0-alpha.0 and in you example configure the plugin like this:
```javascript
plugins: [
      sassPlugin({
        outputStyle: isProd ? 'compressed' : 'expanded',
        // transform: postcssModules({
        //   // ...put here the options for postcss-modules: https://github.com/madyankin/postcss-modules
        // })
        precompile(source, pathname) {
          console.log("precompile:", pathname)
          return source.replace(/(url\(['"])(\.\.?\/)([^'"]+['"]\))/g, `$1${path.dirname(pathname)}/$2$3`)
        }
      })
    ]
```

I look forward to hear if it works in your codebase!

**Comment by Hideman85** [comment] 2021-12-20 08:13
Hi @glromeo thanks for the update and your work :slightly_smiling_face: 
I just tried out and I cannot see the import error with the asset but it could be due to the flooded error that I have now.
Lot of my sass files import a relative `_variables.sass` to get access to the colors, margin and plenty of other variables for the styling.
But now I do have a import issue:
```js
✘ [ERROR] ENOENT: no such file or directory, open 'tmp/project/src/_variables.scss'
  ╷
1 │ @import "../../../variables";
  │         ^^^^^^^^^^^^^^^^^^^^
  ╵
  - 1:9  root stylesheet

    src/components/SharedComponents/CardSelector.tsx:6:7:
      6 │ import './styles/CardSelectorStyles.scss'
```
I note that the logging do not contains a beginning `/` to the absolute path is that normal?

**Comment by glromeo** [comment] 2021-12-20 11:51
hmm... the `url()` substitution shouldn't affect that... can you add the relevant files to https://github.com/Hideman85/esbuild-sass-test-case ?
This would help me debug the new importer logic and come up with a e2e test for a layout like yours

**Comment by Hideman85** [comment] 2021-12-20 14:04
I just ran my test case with dependencies up to date like:
```json
  "devDependencies": {
    "esbuild": "~0.14.6",
    "esbuild-sass-plugin": "~2.0.0-alpha.0"
  },
```

And got this without the need of extra files:
```js
└─$ yarn node build.js                                                                                                                                                                                         1 ⚙
✘ [ERROR] [plugin sass-plugin] ENOENT: no such file or directory, open 'tmp/esbuild-sass-test-case/fonts/fonts.scss'
  ╷
1 │ @import '../fonts/fonts.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
  - 1:9  root stylesheet

    src/index.js:1:7:
      1 │ import './style.scss'
        ╵        ~~~~~~~~~~~~~~

(node:233087) UnhandledPromiseRejectionWarning: Error: Build failed with 1 error:
src/index.js:1:7: ERROR: [plugin: sass-plugin] ENOENT: no such file or directory, open 'tmp/esbuild-sass-test-case/fonts/fonts.scss'
  ╷
1 │ @import '../fonts/fonts.scss';
  │         ^^^^^^^^^^^^^^^^^^^^^
  ╵
  - 1:9  root stylesheet
    at failureErrorWithLog (/tmp/esbuild-sass-test-case/node_modules/esbuild/lib/main.js:1503:15)

```

I seen this:
```js
yarn why esbuild
├─ esbuild-sass-plugin@npm:2.0.0-alpha.0
│  └─ esbuild@npm:0.14.6 (via npm:^0.14.5)
│
└─ test-case@workspace:.
   └─ esbuild@npm:0.14.6 (via npm:~0.14.6)
```

Same output after downgrade, have you tired out? I'm on latest Ubuntu 21.10.

**Comment by glromeo** [comment] 2021-12-20 14:20
looks an issue with the path separators...I am going to try it on my mac. Thanks for the help troubleshooting!

**Comment by glromeo** [comment] 2021-12-20 14:34
please update to https://www.npmjs.com/package/esbuild-sass-plugin/v/2.0.0-alpha.1 !

**Comment by Hideman85** [comment] 2021-12-20 14:46
It does solve the issue but now it remains two points:
- `url(../asset.png)` I guess I just need to update the regex to match urls wothout quotes
- `.myWrapper { @import '../someCssFile' }` that is a common way to import built-in css content an rewrite it in a namespaced matter (you might need me to update my test case)

**Comment by glromeo** [comment] 2021-12-20 23:10
@Hideman85 I see, builtIn is a [Plain CSS @import](https://sass-lang.com/documentation/at-rules/import#plain-css-imports)
Thank you for pointing me at it. Now I understand that I better refactor the url rewrite logic to be performed on the compiled sass rather than the source...

**Comment by glromeo** [comment] 2021-12-23 03:09
@Hideman85 I just released [2.0.0-alpha.3](https://www.npmjs.com/package/esbuild-sass-plugin/v/2.0.0-alpha.3)
which should have a pretty solid import resolution now... I look forward to your feedback!

**Comment by glromeo** [comment] 2021-12-24 03:54
@Hideman85 v2.0.0 has been published... I close this issue now

**Closed by glromeo** 2021-12-24 03:54 UTC

**Comment by Hideman85** [comment] 2022-01-03 13:30
Super thank you so much for your work, I will check out later :)
